version: '3'

services:
  server_one:
    image: server
    environment:
      - APP=first
    ports:
      - "8081:5000"
    networks:
      - load_balancer_network

  server_two:
    image: server
    environment:
      - APP=second
    ports:
      - "8082:5000"
    networks:
      - load_balancer_network

  server_tree:
    image: server
    environment:
      - APP=third
    ports:
      - "8083:5000"
    networks:
      - load_balancer_network

  server_four:
    image: server
    environment:
      - APP=fourth
    ports:
      - "8084:5000"
    networks:
      - load_balancer_network

networks:
  load_balancer_network:
    external: true
